
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export const SceneOfficeModel = (props) => {
  const group = useRef()
  const { nodes, materials } = useGLTF('/uploads_files_2471907_ikea_office_workplace_7 (1).gltf')

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ikea_office_workplace_7_alex_table.geometry}
        material={nodes.ikea_office_workplace_7_alex_table.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ikea_office_workplace_7_alex_big.geometry}
        material={nodes.ikea_office_workplace_7_alex_big.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ikea_office_workplace_7_table_carpet.geometry}
        material={nodes.ikea_office_workplace_7_table_carpet.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ikea_office_workplace_7_journals_1.geometry}
        material={nodes.ikea_office_workplace_7_journals_1.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ikea_office_workplace_7_book_holder.geometry}
        material={nodes.ikea_office_workplace_7_book_holder.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ikea_office_workplace_7_phone.geometry}
        material={nodes.ikea_office_workplace_7_phone.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ikea_office_workplace_7_books_2.geometry}
        material={nodes.ikea_office_workplace_7_books_2.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ikea_office_workplace_7_printer.geometry}
        material={nodes.ikea_office_workplace_7_printer.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ikea_office_workplace_7_27_inch_screen.geometry}
        material={nodes.ikea_office_workplace_7_27_inch_screen.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ikea_office_workplace_7_open_journal.geometry}
        material={nodes.ikea_office_workplace_7_open_journal.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ikea_office_workplace_7_pc.geometry}
        material={nodes.ikea_office_workplace_7_pc.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ikea_office_workplace_7_keyboard.geometry}
        material={nodes.ikea_office_workplace_7_keyboard.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ikea_office_workplace_7_pc_mouse.geometry}
        material={nodes.ikea_office_workplace_7_pc_mouse.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ikea_office_workplace_7_pens.geometry}
        material={nodes.ikea_office_workplace_7_pens.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ikea_office_workplace_7_vase_1.geometry}
        material={nodes.ikea_office_workplace_7_vase_1.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ikea_office_workplace_7_brushes_2.geometry}
        material={nodes.ikea_office_workplace_7_brushes_2.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ikea_office_workplace_7_coffe_cup.geometry}
        material={nodes.ikea_office_workplace_7_coffe_cup.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ikea_office_workplace_7_svensas.geometry}
        material={nodes.ikea_office_workplace_7_svensas.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ikea_office_workplace_7_power_sockets.geometry}
        material={nodes.ikea_office_workplace_7_power_sockets.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ikea_office_workplace_7_calendar.geometry}
        material={nodes.ikea_office_workplace_7_calendar.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ikea_office_workplace_7_journals_2.geometry}
        material={nodes.ikea_office_workplace_7_journals_2.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ikea_office_workplace_7_books_3.geometry}
        material={nodes.ikea_office_workplace_7_books_3.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ikea_office_workplace_7_storrage_box_2.geometry}
        material={nodes.ikea_office_workplace_7_storrage_box_2.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ikea_office_workplace_7_fluns_folders_2.geometry}
        material={nodes.ikea_office_workplace_7_fluns_folders_2.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ikea_office_workplace_7_pictures.geometry}
        material={nodes.ikea_office_workplace_7_pictures.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ikea_office_workplace_7_storrage_box_1.geometry}
        material={nodes.ikea_office_workplace_7_storrage_box_1.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ikea_office_workplace_7_vase_3.geometry}
        material={nodes.ikea_office_workplace_7_vase_3.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ikea_office_workplace_7_paper_box_2.geometry}
        material={nodes.ikea_office_workplace_7_paper_box_2.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ikea_office_workplace_7_paper_box_4.geometry}
        material={nodes.ikea_office_workplace_7_paper_box_4.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ikea_office_workplace_7_storrage_box_3.geometry}
        material={nodes.ikea_office_workplace_7_storrage_box_3.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ikea_office_workplace_7_forso_lamp.geometry}
        material={nodes.ikea_office_workplace_7_forso_lamp.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ikea_office_workplace_7_vase_2.geometry}
        material={nodes.ikea_office_workplace_7_vase_2.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ikea_office_workplace_7_vase_2_sticks.geometry}
        material={nodes.ikea_office_workplace_7_vase_2_sticks.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ikea_office_workplace_7_markus_chair.geometry}
        material={nodes.ikea_office_workplace_7_markus_chair.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ikea_office_workplace_7_fluns_lone_folder_1.geometry}
        material={nodes.ikea_office_workplace_7_fluns_lone_folder_1.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ikea_office_workplace_7_fluns_folders_1.geometry}
        material={nodes.ikea_office_workplace_7_fluns_folders_1.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ikea_office_workplace_7_paper_box_3.geometry}
        material={nodes.ikea_office_workplace_7_paper_box_3.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ikea_office_workplace_7_books_1.geometry}
        material={nodes.ikea_office_workplace_7_books_1.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ikea_office_workplace_7_vases.geometry}
        material={nodes.ikea_office_workplace_7_vases.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ikea_office_workplace_7_fluns_lone_folder_2.geometry}
        material={nodes.ikea_office_workplace_7_fluns_lone_folder_2.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ikea_office_workplace_7_paper_box_1.geometry}
        material={nodes.ikea_office_workplace_7_paper_box_1.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ikea_office_workplace_7_white_books.geometry}
        material={nodes.ikea_office_workplace_7_white_books.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ikea_office_workplace_7_fniss_bin.geometry}
        material={nodes.ikea_office_workplace_7_fniss_bin.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ikea_office_workplace_7_trash_bucket_papers.geometry}
        material={nodes.ikea_office_workplace_7_trash_bucket_papers.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ikea_office_workplace_7_briefcase.geometry}
        material={nodes.ikea_office_workplace_7_briefcase.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ikea_office_workplace_7_round_boxes.geometry}
        material={nodes.ikea_office_workplace_7_round_boxes.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ikea_office_workplace_7_vase_4.geometry}
        material={nodes.ikea_office_workplace_7_vase_4.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ikea_office_workplace_7_vase_5.geometry}
        material={nodes.ikea_office_workplace_7_vase_5.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ikea_office_workplace_7_table_mirror.geometry}
        material={nodes.ikea_office_workplace_7_table_mirror.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ikea_office_workplace_7_painting.geometry}
        material={nodes.ikea_office_workplace_7_painting.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ikea_office_workplace_7_top_boxes.geometry}
        material={nodes.ikea_office_workplace_7_top_boxes.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ikea_office_workplace_7_eket_shelf_2.geometry}
        material={nodes.ikea_office_workplace_7_eket_shelf_2.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ikea_office_workplace_7_eket_shelf.geometry}
        material={nodes.ikea_office_workplace_7_eket_shelf.material}
      />
    </group>
  )
}

useGLTF.preload('/uploads_files_2471907_ikea_office_workplace_7 (1).gltf')